// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhxuilnkeombzquubgst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoeHVpbG5rZW9tYnpxdXViZ3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjU5NTYsImV4cCI6MjA1OTc0MTk1Nn0.t9C6jGl0SHieJCddClEoLVlrB-PDvSbI1tJ-arxqlPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);